### ISSUE TITLE
daemon.err node-red: (node:3213) 

### ISSUE THREAD

**Issue by Matten-Matten** [rdmtc/node-red-contrib-ccu#108]
Hey, ich habe folgendes im Log gefunden:

```
Feb 12 19:08:32 ccu3-webui daemon.err node-red: (node:3213) UnhandledPromiseRejectionWarning: Error: overwritten
Feb 12 19:08:32 ccu3-webui daemon.err node-red:     at Promise (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:2763:55)
Feb 12 19:08:32 ccu3-webui daemon.err node-red:     at new Promise (<anonymous>)
Feb 12 19:08:32 ccu3-webui daemon.err node-red:     at CcuConnectionNode.setValue (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:2753:20)
Feb 12 19:08:32 ccu3-webui daemon.err node-red:     at CcuValue.on [as _inputCallback] (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/nodes/ccu-value.js:98:73)
Feb 12 19:08:32 ccu3-webui daemon.err node-red:     at CcuValue.Node._emitInput (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)
Feb 12 19:08:32 ccu3-webui daemon.err node-red:     at Immediate.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:33)
Feb 12 19:08:32 ccu3-webui daemon.err node-red:     at runCallback (timers.js:705:18)
Feb 12 19:08:32 ccu3-webui daemon.err node-red:     at tryOnImmediate (timers.js:676:5)
Feb 12 19:08:32 ccu3-webui daemon.err node-red:     at processImmediate (timers.js:658:5)
Feb 12 19:08:32 ccu3-webui daemon.err node-red: (node:3213) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 86)
Feb 12 19:11:57 ccu3-webui daemon.err node-red: (node:3213) UnhandledPromiseRejectionWarning: Error: overwritten
```

muss ich mir sorgen machen?

Gruß
Matten Matten

**Comment by hobbyquaker** [comment]
https://github.com/rdmtc/RedMatic/issues/293#issuecomment-570629047
