### ISSUE TITLE
doppelte Homematic Node auf http://127.0.0.1 crashed Node-Red

### ISSUE THREAD

**Issue by Hypnos3** [rdmtc/node-red-contrib-ccu#30]
Ich vermute mal, das RedMatic crashed, wenn man die Konfigurations-Node für die CCU doppelt hat. 

```
Nov 13 13:29:20 homematic-ccu user.info redmatic: Started Node-RED
Nov 13 13:29:24 homematic-ccu daemon.info node-red[29296]: Welcome to Node-RED
Nov 13 13:29:24 homematic-ccu daemon.info node-red[29296]: ===================
Nov 13 13:29:24 homematic-ccu daemon.info node-red[29296]: Node-RED version: v0.19.5
Nov 13 13:29:24 homematic-ccu daemon.info node-red[29296]: Node.js  version: v8.12.0
Nov 13 13:29:24 homematic-ccu daemon.info node-red[29296]: Linux 4.14.71 arm LE
Nov 13 13:29:26 homematic-ccu daemon.info node-red[29296]: Loading palette nodes
Nov 13 13:29:28 homematic-ccu daemon.err cuxd[523]: sendbinrpc(127.0.0.1:2047) - write() Connection refused
Nov 13 13:29:38 homematic-ccu daemon.info node-red[29296]: node-red-contrib-milight-2@1.0.7 started
Nov 13 13:29:41 homematic-ccu daemon.info node-red[29296]: node-red-contrib-ccu version: 1.8.1
Nov 13 13:29:42 homematic-ccu daemon.info node-red[29296]: Dashboard version 2.10.1 started at /addons/red/ui
Nov 13 13:29:43 homematic-ccu daemon.err cuxd[523]: sendbinrpc(127.0.0.1:2047) - write() Connection refused
Nov 13 13:29:46 homematic-ccu daemon.info node-red[29296]: Settings file  : /usr/local/addons/redmatic/lib/settings.js
Nov 13 13:29:46 homematic-ccu daemon.info node-red[29296]: HTTP Static    : /usr/local/sdcard/www
Nov 13 13:29:46 homematic-ccu daemon.info node-red[29296]: Context store  : 'default' [module=memory]
Nov 13 13:29:46 homematic-ccu daemon.info node-red[29296]: Context store  : 'memory' [module=memory]
Nov 13 13:29:46 homematic-ccu daemon.info node-red[29296]: Context store  : 'file' [module=localfilesystem]
Nov 13 13:29:46 homematic-ccu daemon.info node-red[29296]: User directory : /usr/local/addons/redmatic/var
Nov 13 13:29:46 homematic-ccu daemon.warn node-red[29296]: Projects disabled : editorTheme.projects.enabled=false
Nov 13 13:29:46 homematic-ccu daemon.info node-red[29296]: Flows file     : /usr/local/addons/redmatic/var/flows.json
Nov 13 13:29:46 homematic-ccu daemon.info node-red[29296]: Server now running at http://127.0.0.1:1880/addons/red/
Nov 13 13:29:48 homematic-ccu daemon.info node-red[29296]: Starting flows
Nov 13 13:29:49 homematic-ccu daemon.info node-red[29296]: [ccu-connection:Homematic] paramsets loaded from /usr/local/addons/redmatic/var/ccu_paramsets_v2.json
Nov 13 13:29:49 homematic-ccu daemon.info node-red[29296]: [ccu-connection:Homematic] metadata loaded from /usr/local/addons/redmatic/var/ccu_localhost.json
Nov 13 13:29:50 homematic-ccu daemon.info node-red[29296]: [ccu-connection:Homematic] paramsets loaded from /usr/local/addons/redmatic/var/ccu_paramsets_v2.json
Nov 13 13:29:50 homematic-ccu daemon.info node-red[29296]: [ccu-connection:Homematic] metadata loaded from /usr/local/addons/redmatic/var/ccu_localhost.json
Nov 13 13:29:51 homematic-ccu daemon.err node-red[29296]: [change:Say Message] Invalid JSONata expression: Syntax error: "Bis bald"
Nov 13 13:29:52 homematic-ccu daemon.err cuxd[523]: sendbinrpc(127.0.0.1:2047) - write() Connection refused
Nov 13 13:29:52 homematic-ccu user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_6160_BidCos-Wired","CENTRAL","PONG","hm-rpc.1"}]}) on http://127.0.0.1:2048/RPC2:
Nov 13 13:29:52 homematic-ccu user.err hs485d: XmlRpc transport error
Nov 13 13:29:52 homematic-ccu daemon.info node-red[29296]: RedMatic-WebApp started at /addons/red/app
Nov 13 13:29:53 homematic-ccu daemon.info node-red[29296]: Started flows
Nov 13 13:29:53 homematic-ccu daemon.info node-red[29296]: [tcp in:cd99beb7.11b7a] listening on port 8186
Nov 13 13:29:53 homematic-ccu daemon.notice mosquitto[846]: New connection from 127.0.0.1 on port 1883.
Nov 13 13:29:53 homematic-ccu daemon.notice mosquitto[846]: New client connected from 127.0.0.1 as ccu (c1, k60).
Nov 13 13:29:53 homematic-ccu daemon.info node-red[29296]: [mqtt-broker:Mosquitto] Connected to broker: ccu@mqtt://localhost:1883
Nov 13 13:29:54 homematic-ccu daemon.info node-red[29296]: [debug:System Start] 1
Nov 13 13:29:59 homematic-ccu daemon.warn node-red[29296]: [unsafe-function:MiLightControl] STATE
Nov 13 13:30:04 homematic-ccu daemon.info node-red[29296]: [ccu-connection:Homematic] Interfaces: ReGaHSS, BidCos-RF, BidCos-Wired, HmIP-RF, VirtualDevices, CUxD
Nov 13 13:30:04 homematic-ccu daemon.info node-red[29296]: [ccu-connection:Homematic] xmlrpc server listening on http://127.0.0.1:2048
Nov 13 13:30:05 homematic-ccu daemon.info node-red[29296]: [ccu-connection:Homematic] binrpc server listening on binrpc://127.0.0.1:2047
Nov 13 13:30:05 homematic-ccu daemon.info node-red[29296]: [debug:System Start] 2
Nov 13 13:30:05 homematic-ccu daemon.info node-red[29296]: [ccu-connection:Homematic] Interfaces: ReGaHSS, BidCos-RF, BidCos-Wired, HmIP-RF, VirtualDevices, CUxD
Nov 13 13:30:05 homematic-ccu daemon.info node-red[29296]: [ccu-connection:Homematic] xmlrpc server listening on http://127.0.0.1:2048
Nov 13 13:30:05 homematic-ccu daemon.info node-red[29296]: [ccu-connection:Homematic] binrpc server listening on binrpc://127.0.0.1:2047
Nov 13 13:30:05 homematic-ccu daemon.err node-red: 13 Nov 13:30:05 - [red] Uncaught Exception:
Nov 13 13:30:05 homematic-ccu daemon.err node-red: 13 Nov 13:30:05 - Error: listen EADDRINUSE 127.0.0.1:2047
Nov 13 13:30:05 homematic-ccu daemon.err node-red:     at Server.setupListenHandle [as _listen2] (net.js:1360:14)
Nov 13 13:30:05 homematic-ccu daemon.err node-red:     at listenInCluster (net.js:1401:12)
Nov 13 13:30:05 homematic-ccu daemon.err node-red:     at doListen (net.js:1510:7)
Nov 13 13:30:05 homematic-ccu daemon.err node-red:     at _combinedTickCallback (internal/process/next_tick.js:142:11)
Nov 13 13:30:05 homematic-ccu daemon.err node-red:     at process._tickCallback (internal/process/next_tick.js:181:9)
Nov 13 13:30:05 homematic-ccu daemon.notice mosquitto[846]: Socket error on client ccu, disconnecting.
Nov 13 13:31:22 homematic-ccu user.err hs485d: XmlRpcClient error calling event({[methodName:"event",params:{"nr_6160_BidCos-Wired","CENTRAL","PONG","hm-rpc.1"}]}) on http://127.0.0.1:2048/RPC2:
Nov 13 13:31:22 homematic-ccu user.err hs485d: XmlRpc transport error
```

In diese Situation kommt man, wenn man einen Flow über Clipboard aus einer Installation exportiert und wieder in eine andere importiert und Deploy betätigt.
Dabei kam es bei mir zu der doppelten Configuration Node.

**Comment by hobbyquaker** [comment]
leider gar nicht so trivial zu fixen. Die Exception die der xmlrpc/binrpc Server wirft kann ich aufgrund der Asynchronität nicht fangen, den Port zu testen bevor ich createServer aufrufe klappt auch nicht da ich dann in eine race-condition laufe, muss da etwas mehr Zeit reinstecken und ein paar größere Umbauten vornehmen, bitte um Geduld.

**Comment by Hypnos3** [comment]
Kein Problem, lass dir Zeit.
