### ISSUE TITLE
Verbindung zu CCU nicht möglich

### ISSUE THREAD

**Issue by kaeptnslow** [rdmtc/node-red-contrib-ccu#70]
Hallo,

ich habe versucht die Node-Red Version 0.20.2 mit dem node-red-contrib-ccu (2.0.2) Modul zu laufen zu bringen. 

Dazu habe ich einen neuen Docker Container erzeugt und das Modul hinzugefügt.

Hier die Konfiguration:
![CCU Config](https://user-images.githubusercontent.com/48726906/54620687-d5775d00-4a66-11e9-97c5-5abd83cfcdd9.png)

Leider wird keine Verbindung aufgebaut. 
Im Log des Container finde ich folgenden Exception:

2019-03-19 15:41:45,stdout,"(node:23) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
"
2019-03-19 15:41:45,stdout,"(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
"
2019-03-19 15:41:45,stdout,    at process._tickCallback (internal/process/next_tick.js:189:7)

2019-03-19 15:41:45,stdout,    at <anonymous>

2019-03-19 15:41:45,stdout,    at CcuConnectionNode.getRegaData.then (/data/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:390:30)

2019-03-19 15:41:45,stdout,    at CcuConnectionNode.regaPoll (/data/node_modules/node-red-contrib-ccu/nodes/ccu-connection.js:903:29)

2019-03-19 15:41:45,stdout,(node:23) UnhandledPromiseRejectionWarning: TypeError: this.getRegaVariables(...).catch(...).then(...).catch(...).finally is not a function

Das gesamte Log des Containers:
[NodeRed-Latest.log](https://github.com/rdmtc/node-red-contrib-ccu/files/2984236/NodeRed-Latest.log)

Wie gesagt der Container ist "jungfräulich", keine Flow oder etwas anderes.

Viele Grüße
Kai

**Comment by kaeptnslow** [comment]
noch eine Ergänzung: Entfernt man "ReGaHSS" bei der Schnittstellen, läuft es

**Comment by hobbyquaker** [comment]
ist der Zugriff auf die Rega in der CCU Firewall offen? Im Zweifel mal mit Firewalleinstellung „Ports offen“ testen. Ausserdem darf die Authentifizierung nicht aktiviert sein. Zu Docker spezifischen Eigenheiten der Config bitte auch die Beispiele hier im Readme anschauen.

**Comment by hobbyquaker** [comment]
Ah und Dein Log deutet auf ein veraltetes Nodejs hin, das sollte v8 oder besser v10 sein.

**Comment by kaeptnslow** [comment]
die Firewall ist offen, ich nutze auf dem gleichen Docker Host die Version v.0.19.6 und habe dort meinen ganzen Flows. Läuft stabil und fehlerlos.

Das Docker Image habe ich von https://hub.docker.com/r/nodered/node-red-docker/
Dann werde ich mal versuchen eines zu nutzen oder zu bauen welches >= 10.0 ist

**Comment by hobbyquaker** [comment]
Ja, das ich da ne Funktion genutzt hab die es erst ab Node 10 gibt war ein versehen, war mir nicht bewusst. Ich denke ich such da nen anderen (Node 8 kompatiblen) weg, aber da brauch ich noch Zeit für, frühestens am Wochenende.

**Comment by kaeptnslow** [comment]
Ich hab jetzt seit 2 Tagen ein Docker Image mit 10.x im Einsatz. Funktioniert mit Deiner Lösung tadellos! 

Super Projekt und Danke für deinen Einsatz ! 

Ich weiß jetzt nicht wie Du mit Abwärtskompatibilität umgehen möchtest. Meiner Meinung nach wäre es legitim zu sagen, das für den Einsatz in Node-Red >= 0.20 Nodejs >= 10 erforderlich ist.

Bin selbst in der Branche und irgendwann wird es schwierig mit allen Versionen unter einen Hut zu bringen. Dann besser ein klarer Schnitt und weg mit alten Zöpfen.

**Comment by hobbyquaker** [comment]
node-red-contrib-ccu v2.0.6 is node 8 compatible again
